# abb_prov_t <- function(x){
#   x$province[which(x$province == "ON")] <- "Ontario"
#   x$province[which(x$province == "AB")] <- "Alberta"
#   x$province[which(x$province == "MB")] <- "Manitoba"
#   x$province[which(x$province == "BC")] <- "British Columbia"
#   x$province[which(x$province == "NB")] <- "New Brunswick"
#   x$province[which(x$province == "ON")] <- "Ontario"
#   x$province[which(x$province == "NL")] <- "Newfoundland"
#   x$province[which(x$province == "NS")] <- "Nova Scotia"
#   x$province[which(x$province == "NT")] <- "North Western Territories"
#   x$province[which(x$province == "PE")] <- "Prince Edward Island"
#   x$province[which(x$province == "QC")] <- "Quebec"
#   x$province[which(x$province == "SK")] <- "Saskatchewan"
#   x$province[which(x$province == "YT")] <- "Yukon"
#   
#   x <<- x
# }

  if (1 %in% aux){
    imuni$province[which(imuni$province == "ON")] <- "Ontario"
    imuni$province[which(imuni$province == "AB")] <- "Alberta"
    imuni$province[which(imuni$province == "MB")] <- "Manitoba"
    imuni$province[which(imuni$province == "BC")] <- "British Columbia"
    imuni$province[which(imuni$province == "NB")] <- "New Brunswick"
    imuni$province[which(imuni$province == "ON")] <- "Ontario"
    imuni$province[which(imuni$province == "NL")] <- "Newfoundland"
    imuni$province[which(imuni$province == "NS")] <- "Nova Scotia"
    imuni$province[which(imuni$province == "NT")] <- "North Western Territories"
    imuni$province[which(imuni$province == "PE")] <- "Prince Edward Island"
    imuni$province[which(imuni$province == "QC")] <- "Quebec"
    imuni$province[which(imuni$province == "SK")] <- "Saskatchewan"
    imuni$province[which(imuni$province == "YT")] <- "Yukon"
    
    gis$province[which(gis$province == "ON")] <- "Ontario"
    gis$province[which(gis$province == "AB")] <- "Alberta"
    gis$province[which(gis$province == "MB")] <- "Manitoba"
    gis$province[which(gis$province == "BC")] <- "British Columbia"
    gis$province[which(gis$province == "NB")] <- "New Brunswick"
    gis$province[which(gis$province == "ON")] <- "Ontario"
    gis$province[which(gis$province == "NL")] <- "Newfoundland"
    gis$province[which(gis$province == "NS")] <- "Nova Scotia"
    gis$province[which(gis$province == "NT")] <- "North Western Territories"
    gis$province[which(gis$province == "PE")] <- "Prince Edward Island"
    gis$province[which(gis$province == "QC")] <- "Quebec"
    gis$province[which(gis$province == "SK")] <- "Saskatchewan"
    gis$province[which(gis$province == "YT")] <- "Yukon"
    
    manuf$province[which(manuf$province == "ON")] <- "Ontario"
    manuf$province[which(manuf$province == "AB")] <- "Alberta"
    manuf$province[which(manuf$province == "MB")] <- "Manitoba"
    manuf$province[which(manuf$province == "BC")] <- "British Columbia"
    manuf$province[which(manuf$province == "NB")] <- "New Brunswick"
    manuf$province[which(manuf$province == "ON")] <- "Ontario"
    manuf$province[which(manuf$province == "NL")] <- "Newfoundland"
    manuf$province[which(manuf$province == "NS")] <- "Nova Scotia"
    manuf$province[which(manuf$province == "NT")] <- "North Western Territories"
    manuf$province[which(manuf$province == "PE")] <- "Prince Edward Island"
    manuf$province[which(manuf$province == "QC")] <- "Quebec"
    manuf$province[which(manuf$province == "SK")] <- "Saskatchewan"
    manuf$province[which(manuf$province == "YT")] <- "Yukon"
    
    
    
    
  } 
  
  if (2 %in% aux){
    
    imuni2$province[which(imuni2$province == "ON")] <- "Ontario"
    imuni2$province[which(imuni2$province == "AB")] <- "Alberta"
    imuni2$province[which(imuni2$province == "MB")] <- "Manitoba"
    imuni2$province[which(imuni2$province == "BC")] <- "British Columbia"
    imuni2$province[which(imuni2$province == "NB")] <- "New Brunswick"
    imuni2$province[which(imuni2$province == "ON")] <- "Ontario"
    imuni2$province[which(imuni2$province == "NL")] <- "Newfoundland"
    imuni2$province[which(imuni2$province == "NS")] <- "Nova Scotia"
    imuni2$province[which(imuni2$province == "NT")] <- "North Western Territories"
    imuni2$province[which(imuni2$province == "PE")] <- "Prince Edward Island"
    imuni2$province[which(imuni2$province == "QC")] <- "Quebec"
    imuni2$province[which(imuni2$province == "SK")] <- "Saskatchewan"
    imuni2$province[which(imuni2$province == "YT")] <- "Yukon"
    
    gis2$province[which(gis2$province == "ON")] <- "Ontario"
    gis2$province[which(gis2$province == "AB")] <- "Alberta"
    gis2$province[which(gis2$province == "MB")] <- "Manitoba"
    gis2$province[which(gis2$province == "BC")] <- "British Columbia"
    gis2$province[which(gis2$province == "NB")] <- "New Brunswick"
    gis2$province[which(gis2$province == "ON")] <- "Ontario"
    gis2$province[which(gis2$province == "NL")] <- "Newfoundland"
    gis2$province[which(gis2$province == "NS")] <- "Nova Scotia"
    gis2$province[which(gis2$province == "NT")] <- "North Western Territories"
    gis2$province[which(gis2$province == "PE")] <- "Prince Edward Island"
    gis2$province[which(gis2$province == "QC")] <- "Quebec"
    gis2$province[which(gis2$province == "SK")] <- "Saskatchewan"
    gis2$province[which(gis2$province == "YT")] <- "Yukon"
    
    manuf2$province[which(manuf2$province == "ON")] <- "Ontario"
    manuf2$province[which(manuf2$province == "AB")] <- "Alberta"
    manuf2$province[which(manuf2$province == "MB")] <- "Manitoba"
    manuf2$province[which(manuf2$province == "BC")] <- "British Columbia"
    manuf2$province[which(manuf2$province == "NB")] <- "New Brunswick"
    manuf2$province[which(manuf2$province == "ON")] <- "Ontario"
    manuf2$province[which(manuf2$province == "NL")] <- "Newfoundland"
    manuf2$province[which(manuf2$province == "NS")] <- "Nova Scotia"
    manuf2$province[which(manuf2$province == "NT")] <- "North Western Territories"
    manuf2$province[which(manuf2$province == "PE")] <- "Prince Edward Island"
    manuf2$province[which(manuf2$province == "QC")] <- "Quebec"
    manuf2$province[which(manuf2$province == "SK")] <- "Saskatchewan"
    manuf2$province[which(manuf2$province == "YT")] <- "Yukon"
    
    
  }



# country_11_2$province[which(country_11_2$province == "ON")] <- "Ontario"
# country_11_2$province[which(country_11_2$province == "AB")] <- "Alberta"
# country_11_2$province[which(country_11_2$province == "MB")] <- "Manitoba"
# country_11_2$province[which(country_11_2$province == "BC")] <- "British Columbia"
# country_11_2$province[which(country_11_2$province == "NB")] <- "New Brunswick"
# country_11_2$province[which(country_11_2$province == "ON")] <- "Ontario"
# country_11_2$province[which(country_11_2$province == "NL")] <- "Newfoundland"
# country_11_2$province[which(country_11_2$province == "NS")] <- "Nova Scotia"
# country_11_2$province[which(country_11_2$province == "NT")] <- "North Western Territories"
# country_11_2$province[which(country_11_2$province == "PE")] <- "Prince Edward Island"
# country_11_2$province[which(country_11_2$province == "QC")] <- "Quebec"
# country_11_2$province[which(country_11_2$province == "SK")] <- "Saskatchewan"
# country_11_2$province[which(country_11_2$province == "YT")] <- "Yukon"
# 
# country_01_2$province[which(country_01_2$province == "ON")] <- "Ontario"
# country_01_2$province[which(country_01_2$province == "AB")] <- "Alberta"
# country_01_2$province[which(country_01_2$province == "MB")] <- "Manitoba"
# country_01_2$province[which(country_01_2$province == "BC")] <- "British Columbia"
# country_01_2$province[which(country_01_2$province == "NB")] <- "New Brunswick"
# country_01_2$province[which(country_01_2$province == "ON")] <- "Ontario"
# country_01_2$province[which(country_01_2$province == "NL")] <- "Newfoundland"
# country_01_2$province[which(country_01_2$province == "NS")] <- "Nova Scotia"
# country_01_2$province[which(country_01_2$province == "NT")] <- "North Western Territories"
# country_01_2$province[which(country_01_2$province == "PE")] <- "Prince Edward Island"
# country_01_2$province[which(country_01_2$province == "QC")] <- "Quebec"
# country_01_2$province[which(country_01_2$province == "SK")] <- "Saskatchewan"
# country_01_2$province[which(country_01_2$province == "YT")] <- "Yukon"